//users
export const GET_USERS_AD = 'BEGIN GET_USERS_AD(:PD_AD_BIG, :PD_AD_SMALL, :V_CURSOR); END;'
export const INSERT_USER = 'BEGIN INSERT_USER(:USER_ID, :USERAD, :PASSWORD, :USERNAME, :V_CURSOR);END;'
export const GET_USERS = 'BEGIN GET_USERS(:P_USERAD, :P_USERNAME, :P_START_DATE, :P_END_DATE, :V_CURSOR); END;'
export const GET_USER_ID = 'BEGIN GET_USER_ID(:P_USER_ID, :P_USERAD, :P_PASSWORD, :P_USERNAME, :P_CREATED_AT, :P_UPDATED_AT); END;'
export const UPDATE_USER = 'BEGIN UPDATE_USER(:USER_ID, :USERAD, :PASSWORD, :USERNAME, :V_CURSOR);END;'
export const GET_USER_BY_ID = 'BEGIN GET_USER_BY_ID(:P_USER_ID, :V_CURSOR); END;'
export const DELETE_USER = 'BEGIN DELETE_USER(:P_USER_ID, :V_CURSOR); END;'